# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarants', '0002_auto_20171121_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=122, unique=True),
        ),
    ]
